name: Build Stories Index

on:
  push:
    paths:
      - 'stories/*.yaml'
      - 'stories/*.yml'
      - 'build-stories.py'
  pull_request:
    paths:
      - 'stories/*.yaml'
      - 'stories/*.yml'
      - 'build-stories.py'
  workflow_dispatch:

jobs:
  build-stories:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: Build stories index
      run: |
        python build-stories.py
        
    - name: Check if index changed
      id: check-changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.check-changes.outputs.changed == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add stories/index.json stories/README.md
        git commit -m "🤖 Auto-update stories index"
        git push 